### ISSUE TITLE
Anti war? You should anti the USA first

### ISSUE THREAD

**Issue by huxuan0307** [RIAEvangelist/peacenotwar#15]

**Comment by huxuan0307** [comment]
There is no country in the world that makes the most wars than the United States

**Comment by huxuan0307** [comment]
There is no country in the world that makes more wars than the United States

**Comment by nallath** [comment]
I've got a good read for you @huxuan0307: https://en.wikipedia.org/wiki/Whataboutism

**Comment by huxuan0307** [comment]
> I've got a good read for you @huxuan0307: https://en.wikipedia.org/wiki/Whataboutism

@nallath Yeah, the largest war-maker is the peace-lover. Please call on your puppet government enslaved by capitalism to stop invading Somalia. You and the US are both as ridiculous as described in this article.

**Comment by nallath** [comment]
I don't live in the US, nice try. 

Anyhow. Just because there is another thing is worse (or is a hypocrite for saying it) doesn't mean that the initial statement is incorrect. That's another fallacy: https://en.wikipedia.org/wiki/Tu_quoque

So Is the war in Somalia bad? Yes. Is the war in the Ukraine bad? Also yes.

**Comment by Tvde1** [comment]
Then why doesn't the owner of this repo also wipe all american devices? Just Russian devices is kinda lame if you ask me. (I live in neither country btw)
