### ISSUE TITLE
Better Russian/Ukrainian message in the WITH-LOVE-FROM-AMERICA.txt file

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/peacenotwar#2]
I could use some help making a clearer message spreading the ideas of :

1. Peace not war
2. One person can make a difference
3. When more than 1 person does the same thing at the same time it is powerful
4. Forgiveness. The soldiers and people involved on both sides are not the problems. The leaders that command them are.
5. People are not their Nation, just because someone is from a certain country, it does not mean that they agree with or support their leaders.

**Comment by designdrop** [comment]
Here is what I have at the moment. Trying to clean it up and make it more cohesive. 

Let us never forget that Peace is always the goal. War creates a fog, masking tragedy and destruction while robbing generations of precious time to grow and love. 

Let us not forget that people are not their nations or their leaders. We may be separated by imaginary lines on a map but we have more in common with each other than the ones those that choose start wars and cause havoc. 

Do not blame the soldier for the war. They put their boots on every day and await orders from their superiors. 

We must find the strength to forgive one another in the hopes of achieving precious peace. Surely the soldier would instead be home with their loved ones pursuing their dreams. 

As individuals, we may feel insignificant, but when we look beyond our differences and come together we can achieve monumental outcomes.

**Comment by designdrop** [comment]
Here is what I have. Can I get some feedback

War is not the answer, no matter how bad it is. War brings tragedy and destruction, robbing generations of precious moments and hope for the future. The goal should always be peace. 

The soldier puts on their boots for their country, obeying the orders of their government. Find the strength to forgive, come together, and stand up to real injustice and evil.   

We are all connected through humanity and only separated because of geographic lines. We may feel insignificant as individuals but when enough people act with the same intention, we create big movements. 

Do what you think is right, follow your own morals.

May God bless you and your family. Stay safe.

**Comment by RIAEvangelist** [comment]
Feedback tomorrow.

**Comment by RIAEvangelist** [comment]
Planning on using this in the CommonsJS release which is the big one. Should be like half a million messages delivered in a day or two.

**Comment by RIAEvangelist** [comment]
BTW, I don't think I told you, but this is beautiful prepping now.
