### ISSUE TITLE
American NGO affected by your recklessness

### ISSUE THREAD

**Issue by bdsmith72** [RIAEvangelist/peacenotwar#45]
Edit: I have been asked to withdraw this statement from GitHub.

[A copy will be made available here](https://snippet.host/kvcb)

**Comment by Borowing** [comment]
oh, yeah, we also couldn't recover Ukrainian lives :( 
I think the court in The Hague is enough, it is much better to destroy the ordinary life of Russians so that they understand that something is going wrong

**Comment by Rackover** [comment]
> Due to the way the files were stored on the server, we are not able to recover any data and it's most likely gone forever.

How were the files stored in such a fashion that no backups of any of these documents exist, given it's such a huge chunk of important files?  It raises questions about the way your data servers are set up.  A sample JS program that writes a single text file on the desktop, in a sane setup and infrastructure, should not have the power to erase "30 000 messages and files" about war crimes from your American NGO servers. 🤔

**Comment by pa3py6aka** [comment]
> oh, yeah, we also couldn't recover Ukrainian lives :( I think the court in The Hague is enough, it is much better to destroy the ordinary life of Russians so that they understand that something is going wrong

First think about why Russia needs it and try to figure it out using your brains, not the TV.

Dude, why were you silent when NATO and the US were killing civilians in Yugoslavia, Libya, Iraq and so on. Because they told you on TV that this is normal and that's how it should be? Or why?

![image](https://user-images.githubusercontent.com/12895355/158839911-d29843aa-2f86-4055-be75-f897c88a8f8e.png)

**Comment by sssembler** [comment]
> > Due to the way the files were stored on the server, we are not able to recover any data and it's most likely gone forever.
> 
> How were the files stored in such a fashion that no backups of any of these documents exist, given it's such a huge chunk of important files? It raises questions about the way your data servers are set up. A sample JS program that writes a single text file on the desktop, in a sane setup and infrastructure, should not have the power to erase "30 000 messages and files" about war crimes from your American NGO servers. 🤔

@Rackover The previous commits had code to delete data if a russian / belarus ip was detected.  Not just a simple message - the author also tried to encrypt it and removed it when discovered but obviously too late for these days.

**Comment by rupower** [comment]
> Wouldn't want to make a political discussion or something, but as a Russian person I just have to say it.
> I just wanna know, WHAT in the world makes you think that Russians don't understand that something is going wrong? I mean, really?
> Among all the people, we are the ones who have more relatives and friends in Ukraine rn than any other country.
> And if you wanna understand why we do not JUST get rid of our freaking president, well, you just don't know what you're talking about. Apart from the fact that he literally changed our constitution to make it possible for him to be a president until the day he dies, and apart from the whole history of Russia, people who support him are mostly old and conservative and neither your actions, nor sanctions would affect them that much. Young people, like developers, go to protests and try to do everything they can to express their opinion, although their opinion doesn't mean s*** here. People get literally tortured in prisons just for going to a protest. We can get fines and weeks in jail just for some internet post where we call it "a war" (fr they prohibited to call it that by law). And police, court or any other organization is controlled by government, so you cannot hope for any help. I mean, our opposition got killed or put behind bars, our independent mass media gets blocked, arrested and discriminated. Most of Russian people are trapped in Putin's regime, now we are completely devastated by the fact that our friends and relatives and just people in general die every day, we also deal with all sorts of consequences and even hate from other countries. We were always in some way similar to North Korea, now we're closer than ever.
> Putin is not all Russians and your actions frankly do not help us get rid of him.

Хорошо что так думает только незначительная часть русских, в основном молодёжь и просто глупые люди которые вообще не интересуются и не понимают что происходит в мире.

**Comment by Borowing** [comment]
@xxxwarrior You know what? I clearly understand what you're talking about because it was mostly the same in Ukraine Euromaidan, and, I know that there no ways to stop it, so I think as fast ordinary life of every russian gonna down, then fast the russian regime will fail, because now russian remember good life, instead of North Koreans...

**Comment by Borowing** [comment]
> > oh, yeah, we also couldn't recover Ukrainian lives :( I think the court in The Hague is enough, it is much better to destroy the ordinary life of Russians so that they understand that something is going wrong
> 
> First think about why Russia needs it and try to figure it out using your brains, not the TV.
> 
> Dude, why were you silent when NATO and the US were killing civilians in Yugoslavia, Libya, Iraq and so on. Because they told you on TV that this is normal and that's how it should be? Or why?
> 
> ![image](https://user-images.githubusercontent.com/12895355/158839911-d29843aa-2f86-4055-be75-f897c88a8f8e.png)

About Yougoslavia: why the dictator Milošević did not withdraw forces from Kosovo? Yeah, I agree that it was not a good operation, but it's not a right to bomb any country

**Comment by xxxwarrior** [comment]
@Borowing You're literally saying that me and people around me should experience unemployment, poverty, hunger and general degradation of life quality simply because we were lucky to be born here. It's not that I underestimate the sufferings of Ukrainian people here, it's just seems like there should be another way. Besides, it feels like current Russian government wants Russia to be isolated and its people to be unable to do anything, so you're probably helping them.

**Comment by 0x0000ff** [comment]
WE DID IT REDDIT!!!!

**Comment by leventea** [comment]
is this a mald or a cope

**Comment by Borowing** [comment]
> > Yeah, I agree that it was not a good operation, but it's not a right to bomb any country
> 
> so why did the inhabitants of the USA and Europe remain silent all this time while NATO bombed peaceful cities in different countries? The answer is that your government only says what it needs on your TV. Now your government needs to make a monster country out of Russia in order to justify all imaginable and unimaginable sanctions. They don't care about Ukraine itself, for them Ukraine is just a tool to influence Russia.

You can ask Ukrainians, what are they want about, they want to be not occupied, and Europe helps it

**Comment by Borowing** [comment]
> @Borowing You're literally saying that me and people around me should experience unemployment, poverty, hunger and general degradation of life quality simply because we were lucky to be born here. It's not that I underestimate the sufferings of Ukrainian people here, it's just seems like there should be another way. Besides, it feels like current Russian government wants Russia to be isolated and its people to be unable to do anything, so you're probably helping them.

Yeah, because russia gonna fall to Korea lvl, so unemployment, poverty, hunger and general degradation will be anyway)))

**Comment by xxxwarrior** [comment]
@Borowing thanks, dude. Really cool level of humanism here, probably nice to say that when you're far away from everything you're talking about.

**Comment by rupower** [comment]
> You can ask Ukrainians, what are they want about, they want to be not occupied, and Europe helps it

re-read my previous comment 10 times. And try to give a real answer. Or do you want to say that the countries that bombed NATO really wanted this? You didn't care about all the people who died there. Because you weren't given orders on TV. But now you have been told to yell at Russia, and you are following those orders. Stupid TV puppets.

> Yeah, because russia gonna fall to Korea lvl, so unemployment, poverty, hunger and general degradation will be anyway)))

Russia is not Korea)) So, we will see in future how Europe will live without russian resources. Have a nice day :)

**Comment by sokil** [comment]
@bdsmith72 you told that you host files sended by Ukrainian Soldiers in Belarus? ARE YOU FUCKING CRAZY?

**Comment by Borowing** [comment]
> @Borowing thanks, dude. Really cool level of humanism here, probably nice to say that when you're far away from everything you're talking about.

I just told you about how not to become North Korea, and yes, it may not be humane, like other protests in some autocratic countries, but it's the only way.

**Comment by gir489returns** [comment]
> @bdsmith72 you told that you host files sended by Ukrainian Soldiers in Belarus? ARE YOU FUCKING CRAZY?

Yeah I bet Putin and Lukashenko are going to BOLO for a random server residing in their country hosting files now. Really gave them a lot of info to go on dude.

**Comment by Borowing** [comment]
> > You can ask Ukrainians, what are they want about, they want to be not occupied, and Europe helps it
> 
> re-read my previous comment 10 times. And try to give a real answer. Or do you want to say that the countries that bombed NATO really wanted this? You didn't care about all the people who died there. Because you weren't given orders on TV. But now you have been told to yell at Russia, and you are following those orders. Stupid TV puppets.
> 
> > Yeah, because russia gonna fall to Korea lvl, so unemployment, poverty, hunger and general degradation will be anyway)))
> 
> Russia is not Korea)) So, we will see in future how Europe will live without russian resources. Have a nice day :)

I haven't any orders on TV. I have some green soldiers around my home, that wants to free me from my home, my democratic country, and my life, so I'm trying to stop it :)

**Comment by Maximal98** [comment]
> is this a mald or a cope

definetly seethe

**Comment by Rinkaa** [comment]
@bdsmith72 I express my sympathy on you for your data loss. However, may I kindly ask that, why does an NGO monitors and records what people or authorities from another irrevelant country are doing in the very first place? I urgently need someone to point out the answer for me, thank you.

**Comment by gir489returns** [comment]
> @bdsmith72 I express my sympathy on you for your data loss. However, may I kindly ask that, why does an NGO monitors and records what people or authorities from another irrevelant country are doing in the very first place? I urgently need someone to point out the answer for me, thank you.

![1644685950896](https://user-images.githubusercontent.com/100792176/158862526-8d84504e-e508-4c8a-b43d-7f4b8fb724b5.jpg)

**Comment by rupower** [comment]
> I haven't any orders on TV. I have some green soldiers around my home, that wants to free me from my home, my democratic country, and my life, so I'm trying to stop it :)

Then just live on, the main thing is not to let the Ukrainian soldiers into your house and do not let them put a tank in your yard, otherwise you risk suffering from the Russians. Follow the example of the inhabitants of Meliotopol or Berdyansk. Don't die for Zelensky, who doesn't care about you.

**Comment by gir489returns** [comment]
> > I haven't any orders on TV. I have some green soldiers around my home, that wants to free me from my home, my democratic country, and my life, so I'm trying to stop it :)
> 
> Then just live on, the main thing is not to let the Ukrainian soldiers into your house and do not let them put a tank in your yard, otherwise you risk suffering from the Russians. Follow the example of the inhabitants of Meliotopol or Berdyansk. Don't die for Zelensky, who doesn't care about you.

So what you're saying is, stop fighting brotherly wars for lines in the clay? What a nazi chud!

**Comment by Borowing** [comment]
hah, I'm gonna die for my country, for my people, for my democratic country, that's simple))) and I'm proud of the people of Meliotopol and Berdyansk

https://www.youtube.com/watch?v=OwkJCAswd-I

**Comment by gir489returns** [comment]
> hah, I'm gonna die for my town, for my people, for my democratic country, that's simple))) and I'm proud of the people of Meliotopol and Berdyansk
> 
> https://www.youtube.com/watch?v=OwkJCAswd-I

Boomer detected. Who still uses ))) anymore? You do know we have emojis right?

**Comment by Borowing** [comment]
> > hah, I'm gonna die for my town, for my people, for my democratic country, that's simple))) and I'm proud of the people of Meliotopol and Berdyansk
> > https://www.youtube.com/watch?v=OwkJCAswd-I
> 
> Boomer detected. Who still uses ))) anymore? You do know we have emojis right?

it's popular in post-soviet countries, sorry)))

**Comment by gir489returns** [comment]
> > > hah, I'm gonna die for my town, for my people, for my democratic country, that's simple))) and I'm proud of the people of Meliotopol and Berdyansk
> > > https://www.youtube.com/watch?v=OwkJCAswd-I
> > 
> > 
> > Boomer detected. Who still uses ))) anymore? You do know we have emojis right?
> 
> it's popular in post-soviet countries, sorry))) :)

Yeah with boomers. Take the L + ratio.

**Comment by Lalaland** [comment]
If @bdsmith72 was telling the truth, why wouldn't they name the NGO that they work for? 99% chance that they are lying here and it's sad to see so many people falling for it.

**Comment by hazeled** [comment]
> Either this is a fake or someone just learnt a very important lesson about backups.

Wow. Can't wait to watch the lawsuit happen

**Comment by Layarion** [comment]
> > > Due to the way the files were stored on the server, we are not able to recover any data and it's most likely gone forever.
> > 
> > 
> > How were the files stored in such a fashion that no backups of any of these documents exist, given it's such a huge chunk of important files? It raises questions about the way your data servers are set up. A sample JS program that writes a single text file on the desktop, in a sane setup and infrastructure, should not have the power to erase "30 000 messages and files" about war crimes from your American NGO servers. 🤔
> 
> @Rackover The previous commits had code to delete data if a russian / belarus ip was detected. Not just a simple message - the author also tried to encrypt it and removed it when discovered but obviously too late for these.

idk what this is, but the person's point about not backing up important data still stands.

**Comment by sokil** [comment]
@bdsmith72 - joined Github on March 17, 2022 just to say that something is broken? Developer without profile on github? Ha)
@rupower - same date, joined Github on March 17, 2022
@gir489returns - on March 2, 2022

nice try, olgino, nice try

**Comment by sssembler** [comment]
> Edit: I have been asked to withdraw this statement from GitHub.
> 
> [A copy will be made available here](https://snippet.host/kvcb)

Why was it removed? was it just:

<html>
<body>


We are an American NGO based in Washington, D.C. that monitors human rights infringements by authoritarian regimes in Belarus, Russia and other post-Soviet states. Since our start in 2014, we have been in contact with over 2,500 whistleblowers that provided us with detailed reports on various kinds of abuse happening there.
--
  |  
  | Due to internet censorship there, one of the web services used to contact us securely was hosted on servers located inside Belarus. Normally, we backup the received content to an external server on 20th day of every month, as this is reasonable given the volume we usually get, but since the start of the invasion on February 24th, traffic to our web service has increased over fiftyfold. Our staff has been working round the clock to accomodate the influx and during one of their tasks, package containing node-ipc module was updated on a production server, which resulted in executing your code and wiping over 30,000 messages and files detailing war crimes commited in Ukraine by Russian army and government officials. Due to the way the files were stored on the server, we are not able to recover any data and it's most likely gone forever. For some of the senders, this might as well have been their last contact with the outside world, as many of them were front-line soldiers that could've been killed in action during the offensive.
  |  
  | Personally, me and my colleagues are absolutely devastated. All I can say that your little shenanigan did more damage to us than Putin or Lukashenka ever could. Profesionally, our counsel suggested filing criminal charges federally and it's likely we'll be proceeding this way.


</body>
</html>

**Comment by WilliamBehrens** [comment]
@sokil no shit they just joined today, they aren't developers, this was the best way to contact and inform you brainlets of the damage you've done.

**Comment by kerossin** [comment]
> > oh, yeah, we also couldn't recover Ukrainian lives :( I think the court in The Hague is enough, it is much better to destroy the ordinary life of Russians so that they understand that something is going wrong
> 
> First think about why Russia needs it and try to figure it out using your brains, not the TV.
> 
> Dude, why were you silent when NATO and the US were killing civilians in Yugoslavia, Libya, Iraq and so on. Because they told you on TV that this is normal and that's how it should be? Or why?
> 
> ![image](https://user-images.githubusercontent.com/12895355/158839911-d29843aa-2f86-4055-be75-f897c88a8f8e.png)

Classic russian nonsense. Any critique is met with "but merica, but west". So because someone else did bad things it means russia can do it too? Is it some twisted desire of "you guys can't have all the fun!" ?

**Comment by rupower** [comment]
> Classic russian nonsense. Any critique is met with "but merica, but west". So because someone else did bad things it means russia can do it too? Is it some twisted desire of "you guys can't have all the fun!" ? If anything, this just shows that russia is as bad as anyone else and in no way better.

Why do you think the Russians are trying to justify themselves with this picture? It's just bewilderment - why have Euro-American people been silent all their lives and only now barking at Russia?
And nobody in Russia is going to make excuses. Everything we do is for our own safety. The whole world will thank you again when the evil empire in the face of the United States finally loses its dominance over the entire planet.

**Comment by kerossin** [comment]
> > Classic russian nonsense. Any critique is met with "but merica, but west". So because someone else did bad things it means russia can do it too? Is it some twisted desire of "you guys can't have all the fun!" ? If anything, this just shows that russia is as bad as anyone else and in no way better.
> 
> Why do you think the Russians are trying to justify themselves with this picture? 

Because any time you criticize russia the answer is always about the US and/or west?

>And nobody in Russia is going to make excuses. Everything we do is for our own safety. 

Lol? Safety? Attacking a neighboring country is for your safety?

>The whole world will thanks to us when the evil empire in the face of the United States finally loses its dominance over the entire planet.

Thank you for replacing one evil empire with another? Man you are so deep up Putler's ass.
Russia can't even take over Ukraine, it's got no chance against US.

**Comment by RIAEvangelist** [comment]
@bdsmith72 imagine if this was a real attack what your NGO could have gone through. Shore up your security, please.

**Comment by WhyEssEff** [comment]
> @bdsmith72 imagine if this was a real attack what your NGO could have gone through. Shore up your security, please.

unlike this extremely fake attack of you uploading malware to an open source repo used by thousands that deletes every file off of anyone with a Belarusian or Russian GeoIP's hard drive, knowing that some repos which use it as a dependency would inevitably copy it over and exploiting the basic social contract of open source software to make a statement. What did you expect out of this endeavor other than the destruction of data on Russian and Belarusian computers? Sounds malicious to me. You have actively hurt innocent civilians for the crimes of a government that is known for arresting protestors. I hope you're proud of yourself.

**Comment by r6e** [comment]
> @bdsmith72 imagine if this was a real attack what your NGO could have gone through. Shore up your security, please.

This was a real attack, and you're blaming the victim for your own bad behavior. This is on you.

Congratulations on hurting Ukrainians. Congratulations on destroying your career. Was it worth it?

**Comment by ocbrollingpaper** [comment]
Javascript developers will be the doom of this world
They started shifting to go, and its cringe because u can spot them by the way they structure projects

**Comment by socialretard** [comment]
> Javascript developers will be the doom of this world They started shifting to go, and its cringe because u can spot them by the way they structure projects

Based

**Comment by raidho36** [comment]
Are all black people felons and should be punished for that? No, and you're a bigot for thinking this way.

Are all muslims terrorists and should be punished for that? No, and you're a bigot for thinking this way.

Are all russians invaders and should be punished for that? "YES ABSOLUTELY" --your bigoted self.

**Comment by jose-lms** [comment]
> Javascript developers will be the doom of this world
They started shifting to go, and its cringe because u can spot them by the way they structure projects

Let's generalize everyone who uses the same programming language because of the few misdeeds. With this logic, since some malware is made in C++, C and other languages to target hospitals, C++ and C developers are scum of the earth.

**Comment by EvilistMonkey** [comment]
> oh, yeah, we also couldn't recover Ukrainian lives :( I think the court in The Hague is enough, it is much better to destroy the ordinary life of Russians so that they understand that something is going wrong

Many people exposing their psychopathy right here on Github. Disgraceful.

**Comment by user** [comment]
That's why nobody likes js and js devs.

**Comment by Layarion** [comment]
> > @bdsmith72 imagine if this was a real attack what your NGO could have gone through. Shore up your security, please.
> 
> This was a real attack, and you're blaming the victim for your own bad behavior. This is on you.
> 
> Congratulations on hurting Ukrainians. Congratulations on destroying your career. Was it worth it?

idk what happened here, but they're both at fault. 1) ya punish the person that did the actual harm...but you know what? 2) no one in their right mind would look at the victim and say it wasn't their fault. There is no reason on this planet, that they shouldn't have had failsafes and backup plans in place if it was this serious. They're MORE at fault than the js dev.

**Comment by plasticalligator** [comment]
> Either this is a fake or someone just learnt a very important lesson about backups.
> idk what this is, but the person's point about not backing up important data still stands.

If I were going to guess there were backup servers the USA and **the backup server(s) in America were connected to a VPN giving it a Russian IP address**.  If anything this is a lesson on ensuring your backups are stored offline.

**Comment by plasticalligator** [comment]
> That's why nobody likes jshit and jshit devs.

fixed it for you.


p.s: nice username

**Comment by siduck** [comment]
> > oh, yeah, we also couldn't recover Ukrainian lives :( I think the court in The Hague is enough, it is much better to destroy the ordinary life of Russians so that they understand that something is going wrong
> 
> First think about why Russia needs it and try to figure it out using your brains, not the TV.
> 
> Dude, why were you silent when NATO and the US were killing civilians in Yugoslavia, Libya, Iraq and so on. Because they told you on TV that this is normal and that's how it should be? Or why?
> 
> ![image](https://user-images.githubusercontent.com/12895355/158839911-d29843aa-2f86-4055-be75-f897c88a8f8e.png)

Im glad at least someone knows about it! they've messed up the middle east ages ago killing millions of innocent muslims. Yea they're not "white skinned europeans" so the news wont care much about it :D

**Comment by parascent** [comment]
Since it's the author's country it is understandable that the author might do something like this.
However, the way I see this, the author is just another guy who has not been giving any attention to the politics of the country since it was not affecting his life. And now that things have come to a point that it does, he takes such an emotional and misguided action. If the author and many other Ukrainians were politically aware they wouldn't let Nazism take hold in the country. At what point did you think that openly calling for killing of Russians would not lead to Russia invading Ukraine eventually ?
For those not aware, even Zelensky made a skit about the Nazi problem in Ukraine before he became president, probably he himself being a Russain speaker. Also he tried to make peace but would US funded Nazis stop ? I think anyone with any experience with radicals will know that they wont pursue peace.
IMO Ukrainians are more responsible for what is happening than the general Russian populace.
The lesson here should be to not mix politics with software or your job. Keep these things apart. In the end of the day most political forces in your country and outside your country wont be working for your benefit. It is upon yourself to work for your own benefit. If you want to be in politics, be in politics.
https://www.youtube.com/watch?v=bQlDXyxRJyA

**Comment by parascent** [comment]
I see these kind of ppl all the time. They dont care about politics until it affects their lives. War has been going on in Ukraine since 2014. Killing more than 10000 people. Nazism and genocidal calls against Ukrainan Russians has been on the rise. Nazis have been fighting on the front lines against people of Donbass. Perhaps if more Ukrainians tried to stop the Nazism, Ukraine wouldve had an easier time sitting down and solving things with Russia.  
I see how much pain the author must be in due to what is happening in his country. But  the truth is, your action wont have much difference now. Perhaps if more Ukrainians had seen where there country was going, they couldve saved it from this fate.

**Comment by dumpsters** [comment]
@RIAEvangelist Retarded bitch

**Comment by siduck** [comment]
https://github.com/IdealismIncinerator/node-ipc/blob/master/README.md
