### ISSUE TITLE
Thanks you did everything right

### ISSUE THREAD

**Issue by nick-leman** [RIAEvangelist/peacenotwar#55]
russians kill thousands civilians just because of putin. More than 80% supports this war in russia. There are no uninvolved russians in this war. Here is nothing racist, this is just a war.

**Comment by Titaniumtown** [comment]
lol

**Comment by t3xasdev** [comment]
> russians kill thousands civilians just because of putin. More than 80% supports this war in russia. There are no uninvolved russians in this war. Here is nothing racist, this is just a war.

I really hope you’re just baiting what you said. Even if they’re supporting it that doesn’t make it right. People are easily tricked into believing something when propaganda hits them in a certain way. These people are still suffering and don’t deserve their hard drives to be destroyed because of some long haired shit head who added a malicious commit to a node package.

**Comment by EvilistMonkey** [comment]
> russians kill thousands civilians just because of putin. More than 80% supports this war in russia. There are no uninvolved russians in this war. Here is nothing racist, this is just a war.

MORON.
