### ISSUE TITLE
GPLv3 LICENSE

### ISSUE THREAD

**Issue by iebb** [RIAEvangelist/peacenotwar#9]
does node-ipc ("Licensed under MIT license") now requires GPLv3 since it's including this module? 
or would this module be relicensed to a permissive one?

**Comment by RIAEvangelist** [comment]
I'm not completely sure, that is something best left to lawyers. Node-IPC should be fine inn my view because it notated that it includes this module. If it is an issue though, people can always lock the version. This will be removed from node-ipc once there is no reason to include it further.

Great question though. Thanks!
